//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Dao.EntityContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuracion
    {
        public int ConfiguracionID { get; set; }
        public string Nombre { get; set; }
        public byte[] Logo { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Fax { get; set; }
        public string Rnc { get; set; }
        public string Notas { get; set; }
        public Nullable<decimal> Itbis { get; set; }
        public string Representante { get; set; }
        public Nullable<decimal> PorPre1 { get; set; }
        public Nullable<decimal> PorPre2 { get; set; }
        public Nullable<decimal> PorPre3 { get; set; }
        public Nullable<bool> ImpuestoEnProducto { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> Seguro { get; set; }
        public Nullable<decimal> Transporte { get; set; }
        public Nullable<bool> PermitirDescuento { get; set; }
        public Nullable<int> PrinterPredeterminado { get; set; }
    }
}
