//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Dao.EntityContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        public int FacturaID { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> ClienteID { get; set; }
        public Nullable<int> VehiculoID { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> Itbis { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Nota { get; set; }
        public string Prazo { get; set; }
        public string Rnc { get; set; }
        public string Ncf { get; set; }
        public string TipoComprobante { get; set; }
        public string Cliente { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Ano { get; set; }
        public string Ficha { get; set; }
        public string Placa { get; set; }
        public Nullable<System.DateTime> FechaVence { get; set; }
        public Nullable<decimal> PorItbis { get; set; }
        public Nullable<decimal> PorDes { get; set; }
        public Nullable<bool> Eliminada { get; set; }
        public Nullable<decimal> Pagado { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<int> Enumeracion { get; set; }
        public Nullable<decimal> UtilidadBruta { get; set; }
        public Nullable<decimal> UtilidadNeta { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public string CorreoElectronico { get; set; }
        public Nullable<int> VendedorID { get; set; }
        public string Vendedor { get; set; }
        public Nullable<int> CajaID { get; set; }
        public string Cajero { get; set; }
        public Nullable<int> ReporteDeCajaID { get; set; }
        public Nullable<decimal> Recibo { get; set; }
        public Nullable<decimal> Cambio { get; set; }
        public Nullable<bool> AfectarInventario { get; set; }
        public string Estado { get; set; }
        public Nullable<decimal> Seguro { get; set; }
        public Nullable<decimal> PorcientoSeguro { get; set; }
        public Nullable<int> MonedaId { get; set; }
        public Nullable<decimal> Tasa { get; set; }
        public Nullable<System.DateTime> FechaTasa { get; set; }
    }
}
