//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Dao.EntityContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCF
    {
        public int ComprobanteID { get; set; }
        public string Descripcion { get; set; }
        public string NcfFijos { get; set; }
        public string NcfDinamicos { get; set; }
        public Nullable<int> ddsf { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<System.DateTime> Expiracion { get; set; }
        public Nullable<int> Consumidos { get; set; }
        public Nullable<int> CantidadNotifica { get; set; }
    }
}
