//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Dao.EntityContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewAsientos
    {
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Referencia { get; set; }
        public int Id { get; set; }
        public string Comprobante { get; set; }
        public Nullable<decimal> TotalDebito { get; set; }
        public Nullable<decimal> TotalCredito { get; set; }
        public string Cuenta { get; set; }
        public string Comentario { get; set; }
        public Nullable<decimal> Debito { get; set; }
        public Nullable<decimal> Credito { get; set; }
        public string Rnc { get; set; }
        public string DescripcionCta { get; set; }
        public Nullable<bool> Eliminado { get; set; }
    }
}
