//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Dao.EntityContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewHistoricoEstados
    {
        public int EstadoArticuloID { get; set; }
        public Nullable<int> FacturaID { get; set; }
        public string Cliente { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> ClienteID { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> EstadoId { get; set; }
        public Nullable<int> ProductoID { get; set; }
    }
}
