//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFacturaMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compras
    {
        public int CompraID { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> ClienteID { get; set; }
        public Nullable<int> VehiculoID { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> Itbis { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Nota { get; set; }
        public string Prazo { get; set; }
        public string Rnc { get; set; }
        public string Ncf { get; set; }
        public string TipoBienesServicios { get; set; }
        public string Cliente { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Ano { get; set; }
        public string Ficha { get; set; }
        public string Placa { get; set; }
        public Nullable<System.DateTime> FechaVence { get; set; }
        public Nullable<decimal> PorItbis { get; set; }
        public Nullable<decimal> PorDes { get; set; }
        public Nullable<bool> Eliminada { get; set; }
        public Nullable<decimal> Pagado { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<int> Enumeracion { get; set; }
        public string Correo { get; set; }
    }
}
