//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFacturaMvc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FerreteriaDiplomadoEntities : DbContext
    {
        public FerreteriaDiplomadoEntities()
            : base("name=FerreteriaDiplomadoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categoria> categoria { get; set; }
        public virtual DbSet<CategoriasProductos> CategoriasProductos { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Compras> Compras { get; set; }
        public virtual DbSet<detalleVenta> detalleVenta { get; set; }
        public virtual DbSet<factura> factura { get; set; }
        public virtual DbSet<Facturas> Facturas { get; set; }
        public virtual DbSet<Inventario> Inventario { get; set; }
        public virtual DbSet<modoPago> modoPago { get; set; }
        public virtual DbSet<producto> producto { get; set; }
        public virtual DbSet<Proveedores> Proveedores { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<vendedor> vendedor { get; set; }
        public virtual DbSet<Vendedores> Vendedores { get; set; }
        public virtual DbSet<venta> venta { get; set; }
        public virtual DbSet<View_FacturaItemStatus> View_FacturaItemStatus { get; set; }
        public virtual DbSet<ViewAsientos> ViewAsientos { get; set; }
        public virtual DbSet<vwTasasDias> vwTasasDias { get; set; }
    
        public virtual int reporte_factura(string idPedido)
        {
            var idPedidoParameter = idPedido != null ?
                new ObjectParameter("idPedido", idPedido) :
                new ObjectParameter("idPedido", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("reporte_factura", idPedidoParameter);
        }
    
        public virtual ObjectResult<sp_lista_clientes_Result> sp_lista_clientes(Nullable<int> pageIndex, Nullable<int> pageSize, ObjectParameter pageCount)
        {
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("pageIndex", pageIndex) :
                new ObjectParameter("pageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_lista_clientes_Result>("sp_lista_clientes", pageIndexParameter, pageSizeParameter, pageCount);
        }
    
        public virtual ObjectResult<sp_producto_categoria_Result> sp_producto_categoria(string idCategoria)
        {
            var idCategoriaParameter = idCategoria != null ?
                new ObjectParameter("idCategoria", idCategoria) :
                new ObjectParameter("idCategoria", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_producto_categoria_Result>("sp_producto_categoria", idCategoriaParameter);
        }
    
        public virtual ObjectResult<sp_reporte_venta_Result> sp_reporte_venta(Nullable<decimal> idVenta)
        {
            var idVentaParameter = idVenta.HasValue ?
                new ObjectParameter("idVenta", idVenta) :
                new ObjectParameter("idVenta", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_reporte_venta_Result>("sp_reporte_venta", idVentaParameter);
        }
    }
}
