//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFacturaMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int UsuarioID { get; set; }
        public string Nombre { get; set; }
        public string Contrasena { get; set; }
        public string Facturacion { get; set; }
        public string Compras { get; set; }
        public string CuentasPorPagar { get; set; }
        public string CuentasPorCobrar { get; set; }
        public string Usuarios1 { get; set; }
        public string Inventario { get; set; }
        public string Clientes { get; set; }
        public string Cajas { get; set; }
        public string Conduce { get; set; }
        public string Cotizacion { get; set; }
        public string Contabilidad { get; set; }
        public string NotaDeCredito { get; set; }
        public string NotaDeDebito { get; set; }
        public string Configuracion { get; set; }
        public string Tasas { get; set; }
    }
}
